#!/usr/bin/env python3
import socket
import threading
from tqdm import tqdm
import os

check=[]
confirmed=[]
threads=[]
speed_mode=[1,3,5,15,17,51,85,255,257,771,1285,3855,4369,13107,21845,65535]

def createFunc(i):
	if i==0:
		def func(x):
			y=1
			for i in tqdm(range(int(65535/x))):
				with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
					if s.connect_ex((ip, y)) == 0:check.append(str(y));os.system("clear");print("#Ports Detected:");[print(b) for b in check]
				y+=1

	else:
		def func(x):
			for a in range(int(i*(65535/x)+1),int((i+1)*(65535/x))):
				with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
					if s.connect_ex((ip, a+1)) == 0:check.append(str(a+1));os.system("clear");print("#Ports Detected:");[print(b) for b in check]
	return func

scan = [createFunc(i) for i in range(85)]

def checkport(ip,port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex((ip, int(port))) == 0

choice=input(
'''choose as option:
1 - check all ports
2 - manual check
>'''
)

ip=input(
'''
target ip
>''')

print()

if choice=='1':
	speed = input("speed (1~16) (default=7): ")
	if speed == "":speed=7
	for x in range(int(speed)):
		threads.append(threading.Thread(target=scan[x](speed_mode[int(speed)-1])))
	os.system("clear")
	print("#Ports Detected:")
	for thread in threads:thread.start()
	for thread in threads:thread.join()
	if check!=[]:
		[print(b) for b in check]
		print("#Checking for false positives...")
		for port in check:
			if checkport(ip,int(port)):confirmed.append(port)
		if confirmed!=[]:print("Ports",','.join(confirmed),"are open!")
		else:print("No Open Port Found!")
	else:print("No Open Port Found!")
elif choice=='2':
	port=input(
'''
check port
>''')
	if checkport(ip,port):print("Port",port,"is open")
	else:print("Port",port,"is not open")
else:print("Unknown input. Please try again.")
